name: area

services:
  application-server:
    build:
      context: backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: npm start

  # mobile-client:
  #   build:
  #     context: mobile/
  #   volumes:
  #     - shared-volume:/shared
  #   - command: ????

  web-client:
    build:
      context: ./front
    ports:
      - "8081:8081"
    depends_on:
      # - mobile-client
      - application-server
    volumes:
      - shared-volume:/shared
    command: npm run dev

volumes:
  shared-volume: