name: area

services:

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  application-server:
    build:
      context: backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: npm start
    environment:
      MONGO_URI: mongodb://mongo:27017/area-db
    depends_on:
      - mongo

  # mobile-client:
  #   build:
  #     context: mobile/
  #   volumes:
  #     - shared-volume:/shared
  #   - command: ????

  web-client:
    build:
      context: ./front
    ports:
      - "8081:8081"
    depends_on:
      # - mobile-client
      - application-server
    volumes:
      - shared-volume:/shared
    command: npm run dev

volumes:
  shared-volume:
  mongo-data:
