name: area

services:

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - mongo
    env_file:
      - ./backend/.env.docker

  client_mobile:
    build:
      context: ./mobile
    volumes:
      - shared-volume:/shared

  client_web:
    build:
      context: ./front
    ports:
      - "8081:8081"
    volumes:
      - shared-volume:/shared
    command: npm run dev
    depends_on:
      - client_mobile
      - server
    env_file:
      - ./front/.env.docker

volumes:
  shared-volume:
  mongo-data:
